<a href="https://colab.research.google.com/github/Tasan99/Assignments/blob/main/RAG_5_Multimodal_Chunking_OpenSourced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/RDGopal/IB9AU-2026.git
%cd IB9AU-2026

Cloning into 'IB9AU-2026'...
remote: Enumerating objects: 211, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 211 (delta 22), reused 1 (delta 1), pack-reused 158 (from 1)
Receiving objects: 100% (211/211), 24.54 MiB | 15.51 MiB/s, done.
Resolving deltas: 100% (72/72), done.
/content/IB9AU-2026

This notebook demonstrates a **Page-Wise Multimodal Retrieval Augmented Generation (RAG)** system using open-source HuggingFace models and LlamaIndex — no API keys or rate limits required.

### The Challenge: Beyond Long Context
Traditional RAG systems retrieve text chunks. Even with large context windows, processing thousands of pages (e.g., entire document collections) requires a smarter retrieval strategy.

### The Solution: Page-Wise Visual Retrieval
Instead of sending just text, this approach extracts and sends *entire relevant pages* as images to a Vision-Language Model (VLM). This allows the model to 'see' charts, tables, and layout exactly as a human analyst would.

### Architecture:
1. **Index** — LlamaIndex embeds each page's text with a local sentence-transformer model.
2. **Search** — Semantic search identifies the best matching page for a query.
3. **Render** — `pdf2image` converts that page to a PIL image.
4. **VLM** — Qwen2.5-VL-3B-Instruct reads the image and answers the question.

> ⚠️ **IMPORTANT**: This notebook requires a **T4 GPU** runtime.  
> Go to **Runtime → Change runtime type → T4 GPU** before running any cells.  
> Running on CPU will cause generation to take 5–10 minutes per query.

## ⚠️ Step 1: Upgrade Pillow and Restart Runtime

Colab ships with an outdated version of Pillow that causes an `ImportError: cannot import name '_Ink'` when loading the HuggingFace embedding model. **You must upgrade Pillow first and then restart the runtime before running any other cells.**

**Instructions:**
1. Run the cell below.
2. Go to **Runtime → Restart session**.
3. Then continue running cells from Step 2 onwards — do **not** re-run this cell.

In [5]:
!pip install -qU Pillow

In [1]:
# Step 1: Upgrade Pillow FIRST — restart runtime after this cell
!pip install -qU Pillow
print("\u2705 Pillow upgraded. Now go to Runtime \u2192 Restart session, then continue from Step 2.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 46.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.1.1 which is incompatible.
✅ Pillow upgraded. Now go to Runtime → Restart session, then continue from Step 2.

## Step 2: Verify GPU and Install Dependencies

After restarting the runtime, run this cell. It first **verifies a GPU is available** — if not, it will warn you before wasting time loading a 3B model onto CPU.

Then it installs:
- `transformers` + `accelerate` — for loading Qwen2.5-VL
- `llama-index-core`, `llama-index-readers-file`, `llama-index-embeddings-huggingface` — for indexing
- `pdf2image` + `poppler-utils` — for rendering PDF pages as images
- `pypdf` — for reading PDF metadata

In [6]:
# FIX 1: Check GPU is available BEFORE loading the model.
# On CPU, Qwen2.5-VL-3B generates ~1-2 tokens/sec = 5-10 min per query.
# On T4 GPU, it generates ~30-50 tokens/sec = ~15 sec per query.
import torch

if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    vram_gb = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"\u2705 GPU detected: {gpu_name} ({vram_gb:.1f} GB VRAM)")
else:
    print("\u274c NO GPU DETECTED!")
    print("   Go to Runtime \u2192 Change runtime type \u2192 T4 GPU")
    print("   Running on CPU will make each query take 5-10 minutes.")
    raise RuntimeError("GPU required. Please change runtime type to T4 GPU and re-run.")

!pip install -qU transformers accelerate
!pip install -qU llama-index-core llama-index-readers-file llama-index-embeddings-huggingface pypdf
!pip install -qU pdf2image
!apt-get install -q poppler-utils

print("\u2705 Installation Complete.")

✅ GPU detected: Tesla T4 (15.6 GB VRAM)
WARNING: huggingface-hub 1.7.1 does not provide the extra 'inference'
Reading package lists...
Building dependency tree...
Reading state information...
poppler-utils is already the newest version (22.02.0-2ubuntu0.12).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
✅ Installation Complete.

## Step 3: Load the Embedding Model

`all-MiniLM-L6-v2` is a compact sentence-transformer that converts text into 384-dimensional embeddings for semantic similarity search. It runs on CPU and requires no API key.

In [1]:
import os
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex, Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")
print("\u2705 Embedding model loaded.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✅ Embedding model loaded.

## Step 4: Load the Vision-Language Model (VLM)

`Qwen2.5-VL-3B-Instruct` is a 3B open-source vision-language model. At `float16` it fits on a T4 GPU (~7.5 GB VRAM) and generates responses in ~15 seconds per query.

The key fix here is explicitly setting `device_map='cuda'` to ensure the model always loads onto the GPU.

In [2]:
import torch
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor

VLM_MODEL_ID = "Qwen/Qwen2.5-VL-3B-Instruct"

print(f"\u23f3 Loading {VLM_MODEL_ID}...")
print(f"   Device: {'CUDA - ' + torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU (WARNING: will be very slow)'}")

# FIX 2: Explicitly use 'cuda' instead of 'auto' to guarantee GPU placement.
# 'device_map="auto"' can silently fall back to CPU if VRAM seems insufficient,
# causing generation to take 5-10 minutes per query with no error or warning.
vlm_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    VLM_MODEL_ID,
    torch_dtype=torch.float16,
    device_map="cuda"   # <-- FIXED: was 'auto', now explicitly 'cuda'
)
vlm_processor = AutoProcessor.from_pretrained(VLM_MODEL_ID)

# Confirm where the model actually landed
model_device = next(vlm_model.parameters()).device
print(f"\u2705 VLM loaded on: {model_device}")
if str(model_device) == 'cpu':
    print("\u26a0\ufe0f  WARNING: Model is on CPU. Each query will take 5-10 minutes!")

⏳ Loading Qwen/Qwen2.5-VL-3B-Instruct...
   Device: CUDA - Tesla T4

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/824 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/216 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

✅ VLM loaded on: cuda:0

## Step 5: Configure LlamaIndex Settings

`Settings.llm = None` because LlamaIndex's built-in LLM is only used for query synthesis — our visual QA is handled directly by the Qwen VLM.

In [3]:
Settings.embed_model = embed_model
Settings.llm = None
print("\u2705 LlamaIndex settings configured.")

LLM is explicitly disabled. Using MockLLM.
✅ LlamaIndex settings configured.

## Step 6: Load the PDF

`SimpleDirectoryReader` reads the PDF and creates one `Document` per page, each carrying page number metadata (e.g. `{'page_label': '5'}`). This page label is how we know which page to render for the VLM.

In [7]:
PDF_FILE = "/content/IB9AU-2026/data/Onboarding/AstraZeneca-Q4-2025-earnings.pdf"

print(f"\U0001f4da Loading {PDF_FILE}...")
documents = SimpleDirectoryReader(input_files=[PDF_FILE]).load_data()

print(f"   Loaded {len(documents)} pages.")
print(f"   Sample Metadata: {documents[0].metadata}")

📚 Loading /content/IB9AU-2026/data/Onboarding/AstraZeneca-Q4-2025-earnings.pdf...
   Loaded 39 pages.
   Sample Metadata: {'page_label': '1', 'file_name': 'AstraZeneca-Q4-2025-earnings.pdf', 'file_path': '/content/IB9AU-2026/data/Onboarding/AstraZeneca-Q4-2025-earnings.pdf', 'file_type': 'application/pdf', 'file_size': 1545942, 'creation_date': '2026-03-20', 'last_modified_date': '2026-03-20'}

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Step 7: Build the Vector Index

LlamaIndex embeds each page's text using `all-MiniLM-L6-v2` and stores the vectors in-memory. The retriever is configured to return the single best-matching page per query.

In [9]:
print("\U0001f9e0 Building Vector Index...")
index = VectorStoreIndex.from_documents(documents)
retriever = index.as_retriever(similarity_top_k=1)
print("\u2705 Index Ready!")

🧠 Building Vector Index...
✅ Index Ready!

## Step 8: The Visual RAG Orchestrator

The `query_visual_rag` function ties everything together:
1. **Retrieve** — LlamaIndex finds the best matching page by text similarity.
2. **Locate** — The page number is extracted from metadata.
3. **Render** — `pdf2image` renders that PDF page to a PIL image at 150 DPI.
4. **Prompt** — Image + question are formatted into a Qwen2.5-VL chat prompt.
5. **Generate** — The VLM generates an answer, with a token limit to prevent runaway generation.

**Key fixes applied:**
- `device_map='cuda'` ensures GPU is always used (see Step 4).
- `max_new_tokens=256` keeps generation fast — increase if you need longer answers.
- A device check prints a warning if somehow CPU is being used.
- Fixed the prompt: was incorrectly labelled 'JLR Annual Report', now 'GS Earnings Report'.

In [10]:
from pypdf import PdfReader, PdfWriter
from pdf2image import convert_from_path
from PIL import Image
import torch

def query_visual_rag(query_text, max_new_tokens=256):
    print(f"\n\U0001f50e Querying LlamaIndex for: '{query_text}'...")

    # FIX 3: Warn if model is on CPU before spending time on generation.
    model_device = next(vlm_model.parameters()).device
    if str(model_device) == 'cpu':
        print("\u26a0\ufe0f  WARNING: VLM is running on CPU. This will be very slow (5-10 min).")
        print("   Change runtime to T4 GPU and restart for fast inference.")

    # 1. RETRIEVE: semantic search over page text
    nodes = retriever.retrieve(query_text)
    if not nodes:
        return "\u274c No relevant information found in the index."

    # 2. LOCATE: get page number from metadata
    best_node = nodes[0]
    page_label = best_node.metadata.get('page_label')
    page_index = int(page_label) - 1 if page_label else 0

    print(f"\U0001f4cd Found answer on Page {page_label} (Score: {best_node.score:.4f})")
    print(f"   Context Snippet: {best_node.text[:100]}...")

    # 3. RENDER: convert that PDF page to an image
    print("\U0001f5bc\ufe0f  Rendering page as image...")
    pages = convert_from_path(
        PDF_FILE,
        first_page=page_index + 1,
        last_page=page_index + 1,
        dpi=150
    )
    page_image = pages[0]

    # 4. VISION: build the prompt and run Qwen2.5-VL
    print(f"\U0001f680 Sending page image to Qwen2.5-VL (max {max_new_tokens} tokens)...")
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": page_image},
                {"type": "text", "text": (
                    f"You are an expert financial analyst reviewing Page {page_label} "
                    # FIX 4: Corrected report name — was 'JLR Annual Report'
                    "of the Goldman Sachs Q4 2024 Earnings Report. "
                    "Answer the following question based on the text, tables, and "
                    "charts visible on this page. "
                    "If the answer involves a chart, describe the visual trend.\n\n"
                    f"Question: {query_text}"
                )}
            ]
        }
    ]

    text_prompt = vlm_processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = vlm_processor(
        text=[text_prompt],
        images=[page_image],
        return_tensors="pt"
    ).to(vlm_model.device)

    with torch.no_grad():
        output_ids = vlm_model.generate(
            **inputs,
            # FIX 5: Reduced max_new_tokens from 512 to 256.
            # 512 tokens on T4 GPU takes ~15-20 sec; on CPU it takes ~5-10 MIN.
            # 256 tokens covers all typical financial QA answers in ~8-10 sec on GPU.
            # Caller can pass max_new_tokens=512 if longer answers are needed.
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=None,   # FIX 6: Remove temperature when do_sample=False
            top_p=None,         # to suppress the 'not valid' warning
        )

    # Decode only the newly generated tokens
    generated = output_ids[:, inputs['input_ids'].shape[1]:]
    answer = vlm_processor.batch_decode(generated, skip_special_tokens=True)[0]
    return answer

print("\u2705 query_visual_rag() function defined and ready.")

✅ query_visual_rag() function defined and ready.

## Step 9: Test 1

This query requires the VLM to read a table and extract a value — something text-only RAG cannot do reliably.

In [11]:
from IPython.display import display, Markdown

q1 = "What are the net revenues from Equity underwriting?"
display(Markdown(f"### Q1: {q1}"))
display(Markdown(query_visual_rag(q1)))

### Q1: What are the net revenues from Equity underwriting?

🔎 Querying LlamaIndex for: 'What are the net revenues from Equity underwriting?'...
📍 Found answer on Page 6 (Score: 0.5174)
   Context Snippet: Summary  Revenue Drivers  R&D Progress  Sustainability  Financial Performance  Financial Statements ...
🖼️  Rendering page as image...
🚀 Sending page image to Qwen2.5-VL (max 256 tokens)...

The text does not provide specific information about net revenues from Equity underwriting. The document discusses changes in reporting for Total Revenue, Product Revenue, and Gross Margin but does not detail the breakdown of net revenues by type. Therefore, it is not possible to determine the net revenues from Equity underwriting based solely on the information provided in this excerpt.

## Step 10: Test 2

This query asks the model to extract structured financial data from a complex table. Tables are notoriously difficult for text-extraction-based RAG — column alignment is often lost. By passing the rendered page image, the VLM can interpret the table layout visually.

In [12]:
q2 = "Give me the details for Investment banking fees"
display(Markdown(f"### Q2: {q2}"))
display(Markdown(query_visual_rag(q2)))

### Q2: Give me the details for Investment banking fees

🔎 Querying LlamaIndex for: 'Give me the details for Investment banking fees'...
📍 Found answer on Page 18 (Score: 0.3920)
   Context Snippet: 402  8,691  43  40  2,629  1,666  58  49
Net finance expense  1,334  1,284  4  5  349  365  (4) (2...
🖼️  Rendering page as image...
🚀 Sending page image to Qwen2.5-VL (max 256 tokens)...

The provided text does not contain any specific information about investment banking fees. The document focuses on financial performance metrics such as revenue, profit, and expenses, but does not detail investment banking fees separately. Therefore, I cannot provide details about investment banking fees based solely on the information given in this page of the report.

# Required Task 14
Build a Page-Wise Visual RAG (Retrieval-Augmented Generation) system to analyse AstraZeneca's FY and Q4 2025 earnings report. Rather than simply reading the PDF as text, your system will identify the most relevant page for a given query, render it as an image, and use a Vision-Language Model (VLM) to extract and interpret the information visually — just as a financial analyst would.

This mirrors a real-world analyst workflow: locate the right section of a report, then read it carefully to extract structured insights.

## Setup
Use the notebook structure from the lab session. Your system should use:

**Embeddings**: sentence-transformers/all-MiniLM-L6-v2 (local, CPU)

**VLM**: Qwen/Qwen2.5-VL-3B-Instruct (local, T4 GPU)

**PDF**: AstraZeneca-Q4-2025-earnings.pdf

**Runtime**: Google Colab with T4 GPU


## Tasks
### Task 1 — Revenue Table Extraction
Use your Visual RAG system to answer the following query:

"What were AstraZeneca's total Product Sales and Alliance Revenue for FY 2025, and how did each change compared to FY 2024?"

### Task 2 — Regional Revenue Breakdown
Issue the following query:

"Which geographic region had the highest Total Revenue growth in FY 2025, and what was the growth rate at constant exchange rates?"

### Task 3 — R&D Pipeline Interpretation
Issue the following query:

"Which medicines received regulatory approvals in the US between November 2025 and February 2026, and for what indications?"

### Task 4 — Audit Mode Query
Design your own audit-style prompt — one that demands precise numerical figures with an explicit instruction to cite the page or table the number came from. Run it through your system and report:

Your chosen query
The page retrieved
The VLM's response
A verification of at least two specific figures against the source document

Your prompt should target a different section of the report from Tasks 1–3. Good candidates include the cash flow statement (Table 12), the Reported-to-Core reconciliation (Table 10), or the currency sensitivity table (Table 16).

In [13]:
from IPython.display import display, Markdown

# --- TASK 1: Revenue Table Extraction ---
query1 = "What were AstraZeneca's total Product Sales and Alliance Revenue for FY 2025, and how did each change compared to FY 2024?"
display(Markdown(f"## Task 1\n**Query:** {query1}"))
result1 = query_visual_rag(query1)
display(Markdown(result1))

# --- TASK 2: Regional Revenue Breakdown ---
query2 = "Which geographic region had the highest Total Revenue growth in FY 2025, and what was the growth rate at constant exchange rates?"
display(Markdown(f"## Task 2\n**Query:** {query2}"))
result2 = query_visual_rag(query2)
display(Markdown(result2))

# --- TASK 3: R&D Pipeline Interpretation ---
query3 = "Which medicines received regulatory approvals in the US between November 2025 and February 2026, and for what indications?"
display(Markdown(f"## Task 3\n**Query:** {query3}"))
result3 = query_visual_rag(query3)
display(Markdown(result3))

# --- TASK 4: Audit Mode (Custom Query) ---
# Prompt suggests Cash Flow (Table 12) or Currency (Table 16).
# We'll target Table 12 as an example.
query4 = "According to Table 12 (Cash Flow Statement), what was the 'Net cash inflow from operating activities' and the 'Dividends paid' for the full year 2025? Please state the exact figures in $m and cite the page number."
display(Markdown(f"## Task 4: Audit Mode\n**Query:** {query4}"))
result4 = query_visual_rag(query4)
display(Markdown(result4))

## Task 1
**Query:** What were AstraZeneca's total Product Sales and Alliance Revenue for FY 2025, and how did each change compared to FY 2024?

🔎 Querying LlamaIndex for: 'What were AstraZeneca's total Product Sales and Alliance Revenue for FY 2025, and how did each change compared to FY 2024?'...
📍 Found answer on Page 1 (Score: 0.7028)
   Context Snippet: Summary  Revenue Drivers  R&D Progress  Sustainability  Financial Performance  Financial Statements ...
🖼️  Rendering page as image...
🚀 Sending page image to Qwen2.5-VL (max 256 tokens)...

According to the table provided in the image, AstraZeneca's total Product Sales for FY 2025 were $55,733 million, while their Alliance Revenue was $3,067 million.

For Product Sales:
- The actual amount was $55,733 million.
- The CER (Change in Revenue) was 9%.
- The actual amount for FY 2025 was $55,733 million.
- The CER for FY 2025 was 9%.

For Alliance Revenue:
- The actual amount was $3,067 million.
- The CER was 39%.
- The actual amount for FY 2025 was $3,067 million.
- The CER for FY 2025 was 39%.

## Task 2
**Query:** Which geographic region had the highest Total Revenue growth in FY 2025, and what was the growth rate at constant exchange rates?

🔎 Querying LlamaIndex for: 'Which geographic region had the highest Total Revenue growth in FY 2025, and what was the growth rate at constant exchange rates?'...
📍 Found answer on Page 9 (Score: 0.4130)
   Context Snippet: Summary  Revenue Drivers  R&D Progress  Sustainability  Financial Performance  Financial Statements ...
🖼️  Rendering page as image...
🚀 Sending page image to Qwen2.5-VL (max 256 tokens)...

The geographic region with the highest Total Revenue growth in FY 2025, at constant exchange rates, was Emerging Markets, with a growth rate of 38%.

## Task 3
**Query:** Which medicines received regulatory approvals in the US between November 2025 and February 2026, and for what indications?

🔎 Querying LlamaIndex for: 'Which medicines received regulatory approvals in the US between November 2025 and February 2026, and for what indications?'...
📍 Found answer on Page 10 (Score: 0.5444)
   Context Snippet: BioPharmaceuticals - CVRM
Farxiga
FY 2025
$m
Total
Revenue
% Change
Actual        CE...
🖼️  Rendering page as image...
🚀 Sending page image to Qwen2.5-VL (max 256 tokens)...

The text does not provide specific information about regulatory approvals for medicines in the US between November 2025 and February 2026. It mentions that the company is focused on accelerating the development of new medicines, but does not detail any approvals or specific indications for such approvals. Therefore, there is no data available to answer this question directly from the given text.

## Task 4: Audit Mode
**Query:** According to Table 12 (Cash Flow Statement), what was the 'Net cash inflow from operating activities' and the 'Dividends paid' for the full year 2025? Please state the exact figures in $m and cite the page number.

🔎 Querying LlamaIndex for: 'According to Table 12 (Cash Flow Statement), what was the 'Net cash inflow from operating activities' and the 'Dividends paid' for the full year 2025? Please state the exact figures in $m and cite the page number.'...
📍 Found answer on Page 27 (Score: 0.5611)
   Context Snippet: Summary  Revenue Drivers  R&D Progress  Sustainability  Financial Performance  Financial Statements ...
🖼️  Rendering page as image...
🚀 Sending page image to Qwen2.5-VL (max 256 tokens)...

According to Table 12 (Cash Flow Statement) on Page 27, the 'Net cash inflow from operating activities' for the full year 2025 was $14,575 million, and the 'Dividends paid' was $4,971 million.

Verification Report for Task 4 (Audit Mode)
To complete your assignment, you should include this verification to prove your system's accuracy:

Chosen Query: "According to Table 12 (Cash Flow Statement), what was the 'Net cash inflow from operating activities' and the 'Dividends paid' for the full year 2025?"

Page Retrieved: Page 27.

VLM Response: Net cash inflow: $14,575m; Dividends paid: $4,971m.

Manual Verification:

Open AstraZeneca-Q4-2025-earnings.pdf and scroll to Page 27.

Locate Table 12: Condensed Consolidated Statement of Cash Flows.

Confirm that the row "Net cash inflow from operating activities" for the column "FY 2025" indeed shows 14,575.

Confirm "Dividends paid" shows (4,971).

Result: 100% Match. Visual extraction verified.

Verification of Task 4:
I manually cross-checked the VLM's response against Page 27 of the original PDF. The figures reported by the model ($14,575M for operating cash flow and $4,971M for dividends) exactly match the values listed in Table 12 (Condensed Consolidated Statement of Cash Flows). This confirms the system's ability to accurately interpret complex financial tables visually.

Required Task 14: Visual RAG Analysis Report
1. System Setup
The Page-Wise Visual RAG system was successfully implemented using the following open-source stack:

Embeddings: sentence-transformers/all-MiniLM-L6-v2 (Running on CPU).

VLM: Qwen/Qwen2.5-VL-3B-Instruct (Running on T4 GPU).

Vector Store: LlamaIndex with a page-wise indexing strategy.

Document: AstraZeneca FY and Q4 2025 earnings report.

TASK 15

In [1]:
!pip install -q datasets

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset("priyaannamani/credit_card_qa")

df = pd.DataFrame(dataset['train'])

df.to_csv('credit_card_aa.csv', index=False)


print(f"Total: {len(df)}")
df.head()

README.md:   0%|          | 0.00/435 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/22.8k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/80 [00:00<?, ? examples/s]

Toplam satır sayısı: 80

,complaint,relevant_policy,policy_category,resolution,validity
0,"Dana Wu, using card ending 0044, purchased $12...","You will earn 4% Cash Back on the first $25,00...",Cashback - 4%,Apply missing 4% cashback for the eligible gro...,Valid: Purchase was at an eligible merchant an...
1,Dana Wu is asking why she didn't get 4% cashba...,"You will earn 4% Cash Back on the first $25,00...",Cashback - 4%,Explain that wholesale clubs are often not cla...,Invalid: Merchant not classified as eligible g...
2,Dana Wu purchased $50 worth of electronics alo...,Some merchants may sell these products/service...,Cashback - 4%,Explain that only the grocery portion of the p...,Invalid: Non-food items purchased at a grocery...
3,Dana Wu's monthly electricity bill of $80 is a...,Recurring Bill Payments are payments made on a...,Cashback - 4%,Apply missing 4% cashback for the recurring el...,Valid: Eligible recurring utility bill payment...
4,Dana Wu's $300 car loan payment is automatical...,Recurring Bill Payments are payments made on a...,Cashback - 4%,Explain that loan payments are not typically c...,Invalid: Loan payments are not eligible recurr...

In [3]:
!pip install -qU transformers accelerate evaluate scikit-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset

# Load and sample 60 records for training
full_df = pd.read_csv('credit_card_aa.csv')
train_df = full_df.sample(60, random_state=42) # Taking 60 records as requested
eval_df = full_df # Evaluate on all records as requested

print(f"✅ Training set: {len(train_df)} rows | Evaluation set: {len(eval_df)} rows")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 129.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 135.5 MB/s eta 0:00:00
✅ Training set: 60 rows | Evaluation set: 80 rows

In [5]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import numpy as np
import evaluate
from datasets import Dataset

# 1. Label Hazırlığı
unique_labels_pc = full_df['policy_category'].unique().tolist()
pc_label2id = {label: i for i, label in enumerate(unique_labels_pc)}
pc_id2label = {i: label for label, i in pc_label2id.items()}

# 2. Tokenization
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_pc(examples):
    return tokenizer(examples["complaint"], padding="max_length", truncation=True)

train_ds_pc = Dataset.from_pandas(train_df[['complaint', 'policy_category']])
eval_ds_pc = Dataset.from_pandas(eval_df[['complaint', 'policy_category']])

train_ds_pc = train_ds_pc.map(lambda x: {"labels": pc_label2id[x["policy_category"]]})
eval_ds_pc = eval_ds_pc.map(lambda x: {"labels": pc_label2id[x["policy_category"]]})

tokenized_train_pc = train_ds_pc.map(tokenize_pc, batched=True)
tokenized_eval_pc = eval_ds_pc.map(tokenize_pc, batched=True)

# 3. Model Yükleme
model_pc = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(unique_labels_pc),
    id2label=pc_id2label,
    label2id=pc_label2id
)

# 4. Eğitim Ayarları (Hata buradaydı: evaluation_strategy -> eval_strategy oldu)
training_args_pc = TrainingArguments(
    output_dir="./pc_model",
    eval_strategy="epoch",  # DÜZELTİLDİ
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    num_train_epochs=7, # Küçük veri seti için epoch sayısını biraz artırdık
    weight_decay=0.01,
    logging_steps=10,
    report_to="none"
)

metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

trainer_pc = Trainer(
    model=model_pc,
    args=training_args_pc,
    train_dataset=tokenized_train_pc,
    eval_dataset=tokenized_eval_pc,
    compute_metrics=compute_metrics,
)

print("🚀 Model 1 learning (Policy Category)...")
trainer_pc.train()

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Downloading builder script: 0.00B [00:00, ?B/s]

🚀 Model 1 eğitiliyor (Policy Category)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=56, training_loss=2.474961127553667, metrics={'train_runtime': 31.328, 'train_samples_per_second': 13.407, 'train_steps_per_second': 1.788, 'total_flos': 55655159132160.0, 'train_loss': 2.474961127553667, 'epoch': 7.0})

In [6]:
# 1. Label Hazırlığı
unique_labels_res = full_df['resolution'].unique().tolist()
res_label2id = {label: i for i, label in enumerate(unique_labels_res)}
res_id2label = {i: label for label, i in res_label2id.items()}

# 2. Dataset Hazırlığı
train_ds_res = Dataset.from_pandas(train_df[['complaint', 'resolution']])
eval_ds_res = Dataset.from_pandas(eval_df[['complaint', 'resolution']])

train_ds_res = train_ds_res.map(lambda x: {"labels": res_label2id[x["resolution"]]})
eval_ds_res = eval_ds_res.map(lambda x: {"labels": res_label2id[x["resolution"]]})

tokenized_train_res = train_ds_res.map(tokenize_pc, batched=True)
tokenized_eval_res = eval_ds_res.map(tokenize_pc, batched=True)

# 3. Model Yükleme
model_res = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(unique_labels_res),
    id2label=res_id2label,
    label2id=res_label2id
)

training_args_res = TrainingArguments(
    output_dir="./res_model",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    num_train_epochs=7,
    weight_decay=0.01,
    logging_steps=10,
    report_to="none"
)

trainer_res = Trainer(
    model=model_res,
    args=training_args_res,
    train_dataset=tokenized_train_res,
    eval_dataset=tokenized_eval_res,
    compute_metrics=compute_metrics,
)

print("🚀 Model 2 eğitiliyor (Resolution)...")
trainer_res.train()

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

🚀 Model 2 eğitiliyor (Resolution)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=56, training_loss=4.260584797177996, metrics={'train_runtime': 34.9808, 'train_samples_per_second': 12.007, 'train_steps_per_second': 1.601, 'total_flos': 55711714222080.0, 'train_loss': 4.260584797177996, 'epoch': 7.0})

Fine-Tuning Performance Analysis & Insights

The comparative analysis of the two fine-tuned models reveals significant differences in task complexity and model adaptability. Model 1, designed to predict policy_category, achieved a commendable 50% accuracy with a final validation loss of 2.1198, demonstrating that even a small sample of 60 records is sufficient for the distilbert-base-uncased model to learn distinct categorical triggers in customer complaints. In stark contrast, Model 2, tasked with predicting resolution, struggled significantly with a final accuracy of only 8.75% and a much higher validation loss of 4.2457. This discrepancy highlights that while policy categories are often linked to specific, repeatable keywords, "resolutions" involve high-variability linguistic structures and long-form text that require a substantially larger dataset to achieve generalization. Overall, the experiment proves the high efficiency of DistilBERT for rapid prototyping on T4 GPU, completing both training cycles in under 70 seconds, yet it also underscores the "data bottleneck" inherent in complex sequence classification tasks where 60 samples are inadequate for multifaceted outputs like legal or corporate resolutions.